name: Cache Example Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step to create some dummy content in the cache folder
      - name: Prepare cache folder
        run: |
          mkdir -p ~/.cache/example
          echo "Hello cache!" > ~/.cache/example/file.txt

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/example
          key: cache-0a3e3c1

      - name: prime-cache-0a3e3c1
        run: echo "Cache hit? ${{ steps.cache-step.outputs.cache-hit }}"
